////
title: AsciiDoc theme style
date: 2018-01-01
draft: false
tags: [asciidoc]
////

= AsciiDoc theme style
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
// Disable wrapping in listing and literal blocks.
:toc:
:prewrap!:
//User Interface Macros
:experimental:
:icons: font
//Based repository root. hugo will serve generated diagram from this directory
:imagesoutdir: static/post/asciidoc-preview
:stem:

== 23. Tables

.Simple table
[.table-wrapper]
|===
| Cell in column 1, row 1 | Cell in column 2, row 1
| Cell in column 1, row 2 | Cell in column 2, row 2
| Cell in column 1, row 3 | Cell in column 2, row 3
|===


== 32. Admonition

https://blog.olowolo.com/example-site/post/shortcodes/#admonition

https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/9

.exampleblock
****
CAUTION: important content
****

WARNING: Wolpertingers are known to nest in server racks.
Enter at your own risk


[quote, Monty Python and the Holy Grail]
____
Dennis: Come and see the violence inherent in the system. Help! Help! I'm being repressed!

King Arthur: Bloody peasant!

Dennis: Oh, what a giveaway! Did you hear that? Did you hear that, eh? That's what I'm on about! Did you see him repressing me? You saw him, Didn't you?
____

== 33. Sidebar

.After landing the cloaked Klingon bird of prey in Golden Gate park:
[quote, Captain James T. Kirk, Star Trek IV: The Voyage Home]
Everybody remember where we parked.

.AsciiDoc history
****
AsciiDoc was first released in Nov 2002 by Stuart Rackham.
It was designed from the start to be a shorthand syntax
for producing professional documents like DocBook and LaTeX.
****

== 40. Passthroughs

=== 40.1. Passthrough Macros

pass:[content like #{variable} passed directly to the output] followed by normal content.

content with only select substitutions applied: pass:c,a[__<{email}>__]

=== 40.2. Passthrough Blocks


[pass]
<u>underline me</u> is underlined.


//passthrough, hugo will render it
even admonition: https://blog.olowolo.com/example-site/post/shortcodes/

++++
{{% admonition note "I'm title!" false %}}
biu biu biu.
{{% /admonition %}}

{{% admonition info "info" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition tip "tip" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition success "success" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition question "question" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition warning "warning" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition failure "failure" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition danger "danger" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition bug "bug" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition example "example" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition quote "quote" %}}
biu biu biu.
{{% /admonition %}}
++++

=== youtube

pass:[{{< youtube "wC5pJm8RAu4" >}}]

== 44. User Interface Macros

kbd:[Ctrl+Shift+N]


Press the btn:[OK] button when you are finished.

== 47. Callouts

打开 `:icon: font` 属性，配合如下的CSS属性。

[source,css]
----
pre .conum[data-value] {
    position: relative;
    top: -0.125em;
}

.conum[data-value] {
    display: inline-block;
    color: #fff !important;
    background-color: rgba(0,0,0,0.8);
    -webkit-border-radius: 100px;
    border-radius: 100px;
    text-align: center;
    width: 1.67em;
    height: 1.67em;
    font-size: 0.75em;
    line-height: 1.67em;
    font-style: normal;
    font-weight: bold;
}

.conum[data-value]:after {
    content: attr(data-value);
}

.conum[data-value]+b {
    display: none;
}

.colist.arabic {
    font-size: 16px;
}
.colist td:not([class]):first-child {
    padding: 0.4em 0.75em 0;
    padding-right: 0.5em;
    line-height: 1;
    vertical-align: top;
}
.colist td:not([class]):last-child {
    padding: 0.25em 0;
}
----

== demo

https://dave.cheney.net/practical-go/presentations/qcon-china.html

== bibliography

插入引用

cite:[gidenstam2010efficient]

显示某个引用

bibitem:[gidenstam2010efficient]


显示引用列表

bibliography::[]

== ascii diagram

.ditaa
[ditaa, format="svg"]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....

.plantuml
[plantuml, "diagram-classes-demo", svg]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

.graphviz
[graphviz, format="svg"]
---------------------------------------------------------------------
digraph automata_0 {
  size ="8.5, 11";
  node [shape = circle];
  0 [ style = filled, color=lightgrey ];
  2 [ shape = doublecircle ];
  0 -> 2 [ label = "a " ];
  0 -> 1 [ label = "other " ];
  1 -> 2 [ label = "a " ];
  1 -> 1 [ label = "other " ];
  2 -> 2 [ label = "a " ];
  2 -> 1 [ label = "other " ];
  "Machine: a" [ shape = plaintext ];
}
---------------------------------------------------------------------

== stem

[source,asciidoc]
----
[stem]
++++
sqrt(4) = 2
++++
----

[stem]
++++
sqrt(4) = 2
++++

Water (stem:[H_2O]) is a critical component.

.asciimath
[asciimath]
++++
sqrt(4) = 2
++++

.latexmath
latexmath:[C = \alpha + \beta Y^{\gamma} + \epsilon]

http://www.wiris.com/editor/demo/en/developers

latexmath:[\equiv]
