////
title: AsciiDoc theme style
date: 2018-11-15
draft: false
tags: [asciidoc]
////

= AsciiDoc theme style
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
// Disable wrapping in listing and literal blocks.
:toc:
:prewrap!:
//User Interface Macros
:experimental:
:icons: font
//Based repository root. hugo will serve generated diagram from this directory
:imagesoutdir: static/post/asciidoc-preview
:stem:

== Tables

.希腊字母
[cols="^1,3,5"]
|===
|希腊字母小写、大写 |   LaTeX形式             |     MathJax

|       α A         | \alpha A                |   `$\alpha$`: $\alpha$, `$A$`: $A$
|       β B         | \beta B                 |   `$\beta$`: $\beta$, `$B$`: $B$
|       γ Γ         | \gamma \Gamma           |   `$\gamma$`: $\gamma$, `$\Gamma$`: $\Gamma$
|       δ Δ         | \delta \Delta           |   `$\delta$`: $\delta$, `$\Delta$`: $\Delta$
|      ϵ ε E        | \epsilon \varepsilon E  |   `$\epsilon$`: $\epsilon$, `$\varepsilon$`: $\varepsilon$, `$E$`: $E$
|       ζ Z         | \zeta Z                 |   `$\zeta$`: $\zeta$, `$Z$`: $Z$
|       η H         | \eta H                  |   `$\eta$`: $\eta$, `$H$`: $H$
|      θ ϑ Θ        | \theta \vartheta \Theta |   `$\theta$`: $\theta$, `$\vartheta$`: $\vartheta$, `$\Theta$`: $\Theta$
|       ι I         | \iota I                 |   `$\iota$`: $\iota$, `$I$`: $I$
|       κ K         | \kappa K                |   `$\kappa$`: $\kappa$, `$K$`: $K$
|       λ Λ         | \lambda \Lambda         |   `$\lambda$`: $\lambda$, `$\Lambda$`: $\Lambda$
|       μ M         | \mu M                   |   `$\mu$`: $\mu$, `$M$`: $M$
|       ν Ν         | \nu N                   |   `$\nu$`: $\nu$, `$N$`: $N$
|       ξ Ξ         | \xi \Xi                 |   `$\xi$`: $\xi$, `$\Xi$`: $\Xi$
|       o Ο         | o O                     |   `$o$`: $o$, `$O$`: $O$
|       π Π         | \pi \Pi                 |   `$\pi$`: $\pi$, `$\Pi$`: $\Pi$
|      ρ ϱ P        | \rho \varrho P          |   `$\rho$`: $\rho$, `$\varrho$`: $\varrho$, `$P$`: $P$
|       σ Σ         | \sigma \Sigma           |   `$\sigma$`: $\sigma$, `$\Sigma$`: $\Sigma$
|       τ T         | \tau T                  |   `$\tau$`: $\tau$, `$T$`: $T$
|       υ Υ         | \upsilon \Upsilon       |   `$\upsilon$`: $\upsilon$, `$\Upsilon$`: $\Upsilon$
|      ϕ φ Φ        | \phi \varphi \Phi       |   `$\phi$`: $\phi$, `$\varphi$`: $\varphi$, `$\Phi$`: $\Phi$
|       χ X         | \chi X                  |   `$\chi$`: $\chi$, `$X$`: $X$
|       ψ Ψ         | \psi \Psi               |   `$\psi$`: $\psi$, `$\Psi$`: $\Psi$
|       ω Ω         | \omega \Omega           |   `$\omega$`: $\omega$, `$\Omega$`: $\Omega$
|===

https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference

https://zh.wikipedia.org/wiki/%E5%B8%8C%E8%85%8A%E5%AD%97%E6%AF%8D

== Mathematical Symbols

Mathematical logic: https://en.wikipedia.org/wiki/List_of_logic_symbols

http://detexify.kirelabs.org/symbols.html

https://pic.plover.com/MISC/symbols.pdf

https://tex.stackexchange.com/questions/58098/what-are-all-the-font-styles-i-can-use-in-math-mode

=== stem

* block
+
[source,asciidoc]
----
[stem]
++++
sqrt(4) = 2
++++
----
+
Render result:
+
[stem]
++++
sqrt(4) = 2
++++

* inline steam
+
Water (stem:[H_2O]) is a critical component.

=== asciimath

[source,asciimath]
----
[asciimath]
++++
sqrt(4) = 2
++++
----

Render result:

[asciimath]
++++
sqrt(4) = 2
++++

=== latexmath

[source,latexmath]
----
latexmath:[C = \alpha + \beta Y^{\gamma} + \epsilon]

latexmath:[\equiv]

\mathfrak{ABCDEFGHIJKLMNOPQRSTUVWXYZ}
----

Render result:

latexmath:[C = \alpha + \beta Y^{\gamma} + \epsilon]

latexmath:[\equiv]

latexmath:[\mathfrak{ABCDEFGHIJKLMNOPQRSTUVWXYZ}]

=== Mathematical logic

[latexmath]
++++
\frac{
 \begin{matrix}
 \frac{}{A \ true} u \\
 \vdots \\
 P \ true
 \end{matrix}
 \quad
 \begin{matrix}
 \frac{}{A \ true} u \\
 \vdots \\
 \lnot P \ true
 \end{matrix}
}{\lnot A \ true} \lnot I^u
\qquad
\frac{\lnot A \ true \quad A \ true}{C \ true} \lnot E
++++


++++
<script type="math/tex; mode=document">% <![CDATA[
\begin{alignat}{1}

\newcommand{\moduleLeftDash}{\hspace*{-\boxsep}\raisebox{-\boxlineht}[0pt][0pt]{\rule[.5ex]{\boxrulewd}{\boxlineht}}\boxrule\hspace*{.4em }}
\newcommand{\boxrule}{\leaders\hrule height \boxruleht depth \boxruledp \hfill\mbox{}}

\newcommand{\implies}{\Rightarrow}

\Rightarrow

\lower 4.3pt \ulcorner\!\! \;AAA

\end{alignat} %]]></script>

<script type="math/tex; mode=display">% <![CDATA[ \\
\begin{alignat}{1}
&&\phantom{XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}\\
&\rlap{\UL\H\H \H\H \H\H\H\H \H\H \H\H \H\H  \H\H \H\H \H\H \H\H \H\;\;\MODULE Vector3D \H\H\H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\!\H \UR}\\
& & \CONSTANTS ElemPlus(\_,\_), ElemMinus(\_,\_)\\
& & \LOCAL ConsVector1(seq) \defeq [x \mapsto seq[1], y \mapsto seq[2], z \mapsto seq[3]]\\
& & \LOCAL Elem1(v, i) \defeq \CASE i = 1 \to v.x \;\Box\; i = 2 \to v.y \;\Box\;i=3 \to v.z\\
& &\\
& & \comment{Export $``$opaque" operators}\\
& & ConsVector(seq) \defeq ConsVector1(seq)\\
& & Elem(v, i) \defeq Elem1(v, i)\\
& &\\
& & \INSTANCE VectorSpace \;\;\;\;\WITH Dim \leftarrow 3\\
&\rlap{\LL\H\H\H\H\H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\LR}
\end{alignat} %]]></script>

<script type="math/tex">% <![CDATA[ \\
\begin{alignat}{1}
&\phantom{XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}\\
\rlap{\UL\H\H \H\H \H\H\H\H \H\H \H\H \H\H  \H\H \H\H \H\H \H\H \H\;\;\MODULE Vector3D \H\H\H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\!\H \UR}\\
 & \CONSTANTS ElemPlus(\_,\_), ElemMinus(\_,\_)\\
 & \INSTANCE VectorSpace \;\;\;\;\WITH Dim \leftarrow 3\\
\rlap{\LL\H\H\H\H\H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H \H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\H\LR}
\end{alignat} %]]></script>
++++


++++
<script type="math/tex; mode=display">% <![CDATA[ \\
\begin{alignat}{1}
\sigma_1  &= x + y                                   & \sigma_2  &= \frac{x}{y} \\
\sigma_1' &= \frac{\partial x + y}{\partial x} \quad & \sigma_2' &= \frac{\partial \frac{x}{y}}{\partial x} \\
\end{alignat}
</script>
++++

== Admonition

//https://blog.olowolo.com/example-site/post/shortcodes/#admonition

//https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/9

.exampleblock
****
CAUTION: important content
****

WARNING: Wolpertingers are known to nest in server racks.
Enter at your own risk


[quote, Monty Python and the Holy Grail]
____
Dennis: Come and see the violence inherent in the system. Help! Help! I'm being repressed!

King Arthur: Bloody peasant!

Dennis: Oh, what a giveaway! Did you hear that? Did you hear that, eh? That's what I'm on about! Did you see him repressing me? You saw him, Didn't you?
____

//passthrough, hugo will render it
// even admonition: https://blog.olowolo.com/example-site/post/shortcodes/

++++
{{% admonition note "I'm title!" false %}}
biu biu biu.
{{% /admonition %}}

{{% admonition info "info" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition tip "tip" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition success "success" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition question "question" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition warning "warning" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition failure "failure" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition danger "danger" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition bug "bug" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition example "example" %}}
biu biu biu.
{{% /admonition %}}

{{% admonition quote "quote" %}}
biu biu biu.
{{% /admonition %}}
++++

== Passthroughs

=== Passthrough Macros

pass:[content like #{variable} passed directly to the output] followed by normal content.

content with only select substitutions applied: pass:c,a[__<{email}>__]

=== Passthrough Blocks
[pass]
<u>underline me</u> is underlined by html tag &lt;u&gt;..&lt;/u&gt;

=== Youtube

pass:[{{< youtube "6Sa-wSwCkY8" >}}]

== User Interface Macros

kbd:[Ctrl+Shift+N]


Press the btn:[OK] button when you are finished.


== bibliography

插入引用

cite:[gidenstam2010efficient]

显示某个引用

bibitem:[gidenstam2010efficient]


显示引用列表

bibliography::[]

== Diagram by Coding

.ditaa
https://github.com/stathissideris/ditaa
[ditaa, format="svg"]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....

.plantuml
[plantuml, "diagram-classes-demo", svg]
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

.graphviz
[graphviz, format="svg"]
---------------------------------------------------------------------
digraph automata_0 {
  size ="8.5, 11";
  node [shape = circle];
  0 [ style = filled, color=lightgrey ];
  2 [ shape = doublecircle ];
  0 -> 2 [ label = "a " ];
  0 -> 1 [ label = "other " ];
  1 -> 2 [ label = "a " ];
  1 -> 1 [ label = "other " ];
  2 -> 2 [ label = "a " ];
  2 -> 1 [ label = "other " ];
}
---------------------------------------------------------------------

一些绘图工具：

* ascii to svg: https://github.com/ivanceras/svgbob
* 流程图、UML图( vs plantUML）、甘特图 、轨道图: https://github.com/mermaid-js/mermaid-cli
* 结构图、DAG等等(graphviz): https://www.graphviz.org/
* digital timing diagram : https://github.com/wavedrom/wavedrom

